name: 'log4j2 validator'
description: 'check if log4j kafka blocking configuration is false'
author: 'tommy810pp'
inputs:
  WORKSPACE:
    description: 'workspace'
  REPOSITORY:
    description: 'repository'
runs:
  using: 'node12'
  main: './main.js'
